<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pages = [
            [
                'id' => 1,
                'is_default' => false,
                'page_id' => null,
                'language_id' => 37,
                'title' => 'Privacy Policy',
                'slug' => 'privacy-policy',
                'content' => 'Our privacy policy',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'is_default' => false,
                'page_id' => null,
                'language_id' => 37,
                'title' => 'Legal Notice',
                'slug' => 'legal-notice',
                'content' => 'Legal Notice',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'is_default' => false,
                'page_id' => null,
                'language_id' => 37,
                'title' => 'Terms of Service',
                'slug' => 'terms-of-service',
                'content' => 'Terms of Service',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'is_default' => false,
                'page_id' => null,
                'language_id' => 37,
                'title' => 'About',
                'slug' => 'about',
                'content' => 'About our project',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'is_default' => false,
                'page_id' => null,
                'language_id' => 37,
                'title' => 'Testimonials',
                'slug' => 'testimonials',
                'content' => 'Some testimonials',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'is_default' => false,
                'page_id' => null,
                'language_id' => 37,
                'title' => 'Features',
                'slug' => 'features',
                'content' => 'Features of the KURSARO system',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'is_default' => false,
                'page_id' => null,
                'language_id' => 37,
                'title' => 'How it works',
                'slug' => 'how-it-works',
                'content' => 'Brief description of the system functionality',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'is_default' => true,
                'page_id' => 1,
                'language_id' => 37,
                'title' => 'Privacy Policy',
                'slug' => 'privacy-policy',
                'content' => 'Our privacy policy',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'is_default' => true,
                'page_id' => 2,
                'language_id' => 37,
                'title' => 'Legal Notice',
                'slug' => 'legal-notice',
                'content' => 'Legal Notice',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'is_default' => true,
                'page_id' => 3,
                'language_id' => 37,
                'title' => 'Terms of Service',
                'slug' => 'terms-of-service',
                'content' => 'Terms of Service',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'is_default' => true,
                'page_id' => 4,
                'language_id' => 37,
                'title' => 'About',
                'slug' => 'about',
                'content' => 'About our project',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'is_default' => true,
                'page_id' => 5,
                'language_id' => 37,
                'title' => 'Testimonials',
                'slug' => 'testimonials',
                'content' => 'Some testimonials',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'is_default' => true,
                'page_id' => 6,
                'language_id' => 37,
                'title' => 'Features',
                'slug' => 'features',
                'content' => 'Features of the KURSARO system',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'is_default' => true,
                'page_id' => 7,
                'language_id' => 37,
                'title' => 'How it works',
                'slug' => 'how-it-works',
                'content' => 'Brief description of the system functionality',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'is_default' => false,
                'page_id' => 1,
                'language_id' => 42,
                'title' => 'Privateca Politiko',
                'slug' => 'privateca-politiko',
                'content' => 'Nia Privateca Politiko',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'is_default' => false,
                'page_id' => 2,
                'language_id' => 42,
                'title' => 'Leĝa Avizo',
                'slug' => 'lega-avizo',
                'content' => 'Nia Leĝa Avizo',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'is_default' => false,
                'page_id' => 3,
                'language_id' => 42,
                'title' => 'Servokondiĉoj',
                'slug' => 'servokondicoj',
                'content' => 'Niaj Servokondiĉoj',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'is_default' => false,
                'page_id' => 4,
                'language_id' => 42,
                'title' => 'Pri la projekto',
                'slug' => 'pri-la-projekto',
                'content' => 'Informoj pri la projekto',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'is_default' => false,
                'page_id' => 5,
                'language_id' => 42,
                'title' => 'Atestoj',
                'slug' => 'atestoj',
                'content' => 'Atestoj de kelkaj vizitantoj',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'is_default' => false,
                'page_id' => 6,
                'language_id' => 42,
                'title' => 'Karakterizaĵoj',
                'slug' => 'karakterizajxoj',
                'content' => 'Kiuj karakteristikoj havas la sistemo',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'is_default' => false,
                'page_id' => 7,
                'language_id' => 42,
                'title' => 'Kiel sistemo funkcias',
                'slug' => 'kiel-sistemo-funkcias',
                'content' => 'Priskribo pri kiel la sistemo funkcias',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        Page::insert($pages);
    }
}
