<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    public function run()
    {
        $permissions = [
            [
                'id'    => 1,
                'title' => 'user_management_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 2,
                'title' => 'permission_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 3,
                'title' => 'permission_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 4,
                'title' => 'permission_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 5,
                'title' => 'permission_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 6,
                'title' => 'permission_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 7,
                'title' => 'role_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 8,
                'title' => 'role_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 9,
                'title' => 'role_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 10,
                'title' => 'role_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 11,
                'title' => 'role_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 12,
                'title' => 'user_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 13,
                'title' => 'user_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 14,
                'title' => 'user_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 15,
                'title' => 'user_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 16,
                'title' => 'user_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 17,
                'title' => 'language_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 18,
                'title' => 'language_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 19,
                'title' => 'language_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 20,
                'title' => 'language_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 21,
                'title' => 'language_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 22,
                'title' => 'index_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 23,
                'title' => 'system_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 24,
                'title' => 'page_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 25,
                'title' => 'page_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 26,
                'title' => 'page_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 27,
                'title' => 'page_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 28,
                'title' => 'page_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 29,
                'title' => 'home_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 30,
                'title' => 'home_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 31,
                'title' => 'home_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 32,
                'title' => 'home_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 33,
                'title' => 'home_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 34,
                'title' => 'category_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 35,
                'title' => 'category_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 36,
                'title' => 'category_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 37,
                'title' => 'category_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 38,
                'title' => 'category_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 39,
                'title' => 'group_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 40,
                'title' => 'course_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 41,
                'title' => 'course_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 42,
                'title' => 'course_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 43,
                'title' => 'course_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 44,
                'title' => 'course_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 45,
                'title' => 'promo_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 46,
                'title' => 'banner_spot_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 47,
                'title' => 'banner_spot_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 48,
                'title' => 'banner_spot_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 49,
                'title' => 'banner_spot_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 50,
                'title' => 'banner_spot_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 51,
                'title' => 'banner_type_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 52,
                'title' => 'banner_type_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 53,
                'title' => 'banner_type_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 54,
                'title' => 'banner_type_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 55,
                'title' => 'banner_type_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 56,
                'title' => 'banner_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 57,
                'title' => 'banner_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 58,
                'title' => 'banner_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 59,
                'title' => 'banner_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 60,
                'title' => 'banner_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 61,
                'title' => 'back_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 62,
                'title' => 'feedback_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 63,
                'title' => 'feedback_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 64,
                'title' => 'feedback_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 65,
                'title' => 'feedback_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 66,
                'title' => 'feedback_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 67,
                'title' => 'prospect_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 68,
                'title' => 'prospect_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 69,
                'title' => 'prospect_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 70,
                'title' => 'prospect_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 71,
                'title' => 'prospect_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 72,
                'title' => 'contact_type_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 73,
                'title' => 'contact_type_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 74,
                'title' => 'contact_type_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 75,
                'title' => 'contact_type_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 76,
                'title' => 'contact_type_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 77,
                'title' => 'contact_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 78,
                'title' => 'contact_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 79,
                'title' => 'contact_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 80,
                'title' => 'contact_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 81,
                'title' => 'contact_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 82,
                'title' => 'course_feature_create',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 83,
                'title' => 'course_feature_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 84,
                'title' => 'course_feature_show',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 85,
                'title' => 'course_feature_delete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 86,
                'title' => 'course_feature_access',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 87,
                'title' => 'profile_password_edit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Permission::insert($permissions);
    }
}
