<link href="{{ asset('assets/backend/default/bootstrap/4.1.3/css/bootstrap.min.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/backend/default/font-awesome/4.7.0/css/font-awesome.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/backend/default/font-awesome/5.2.0/css/all.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/backend/default/datatables/1.10.19/css/jquery.dataTables.min.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/backend/default/datatables/1.10.19/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/backend/default/buttons/1.2.4/buttons.dataTables.min.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/backend/default/select/1.3.0/css/select.dataTables.min.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/backend/default/select2/4.0.5/css/select2.min.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/backend/default/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/backend/default/coreui/3.2/dist/css/coreui.min.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/backend/default/dropzone/5.5.1/min/dropzone.min.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/backend/default/perfect-scrollbar/1.5.0/css/perfect-scrollbar.min.css') }}" rel="stylesheet" />
